CREATE TABLE Datapoint (
  id INTEGER CONSTRAINT PK_DATAPOINT PRIMARY KEY AUTOINCREMENT NOT NULL,
  temperature FLOAT NOT NULL,
  date INTEGER DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE INDEX Datapoint_date ON Datapoint(date);
